# Generated by Django 5.1.7 on 2025-03-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
