# Generated by Django 5.1.7 on 2025-03-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_table_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_booked',
        ),
    ]
